# nixpacks.toml

# Fase 'setup' untuk menginstal paket yang dibutuhkan
[phases.setup]
nixPkgs = ["...", "php82Extensions.nginx", "php82"]

# Fase 'build' untuk menjalankan perintah build
[phases.build]
cmds = ["...", "composer install --no-dev --optimize-autoloader"]

# Fase 'start' untuk mendefinisikan bagaimana aplikasi dijalankan
[start]
cmd = "...", "nginx -c /app/nginx.conf & php-fpm"

# === BAGIAN TERPENTING UNTUK MENGATASI ERROR ANDA ===
[phases.start.preStart]
cmds = [
    "sed -i 's/client_max_body_size 2m;/client_max_body_size 10m;/g' /etc/nginx/nginx.conf",
    "sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 10M/g' /etc/php/8.2/fpm/php.ini",
    "sed -i 's/post_max_size = 8M/post_max_size = 10M/g' /etc/php/8.2/fpm/php.ini"
]